### ISSUE TITLE
rabbitmq messages and multiple instances

### ISSUE THREAD

**Issue by ekapassa** [sonata-nfv/tng-sla-mgmt#252]
- all instances should NOT consume the message - only the interested one

-  https://stackoverflow.com/questions/48956267/rabbitmq-multiple-instances-reading-from-the-same-topic

- http://www.rabbitmq.com/tutorials/tutorial-two-java.html

- http://www.rabbitmq.com/tutorials/tutorial-two-python.html

- http://www.rabbitmq.com/confirms.html

**Comment by mtouloup** [comment]
Useful Links:
[https://www.rabbitmq.com/tutorials/tutorial-two-python.html](url) 
[https://www.rabbitmq.com/tutorials/tutorial-two-java.html](url)
