### ISSUE TITLE
SLA manager private DB in PostgreSQL

### ISSUE THREAD

**Issue by mtouloup** [sonata-nfv/tng-sla-mgmt#350]
Currently SLA manager is using GK's database in PostgreSQL named "gatekeeper". So i think its a better approach to create it's own database named "sla_manager". 

I guess we need to define it somewhere in tng-devops but i would need some help 💃

**Comment by luishens01** [comment]
Hi, 
in my case I use the son-postgres with the Platform Adapter. 

The creation of the table/s and the population is done in the PA container: Everytime the PA container is started/restarted/redeployed, it will, for example, try to create the tables, if they exists, it does nothing.

So my suggestion is this: 
Add the operations in you container (create db,tables, populate,etc), so you will not need to change the tng-devops

What do you think ?

Kind Regards
Luis

**Comment by mtouloup** [comment]
Hi, this is exactly what we are doing. But... If you can see [here: ](https://github.com/sonata-nfv/tng-sla-mgmt/blob/master/sla-template-generator/src/main/java/eu/tng/correlations/db_operations.java#L82) the connection method of the sla manager is taking also as parameter the name of the DB.... So i guess, when the postgre container is coming up, its supposed to create a database for the sla manager as well.

In your case, do you create the DB in the PA's code??

**Comment by luishens01** [comment]
Hi, 
in the environment file, you can see the env variables:

https://github.com/sonata-nfv/tng-devops/blob/master/host_vars/pre-int-vnv-bcn.5gtango.eu

gtk_db_name: gatekeeper
gtk_db_user: sonatatest
gtk_db_pass: !vault |

mon_db_name: monitoring
mon_db_user: monitoringuser
mon_db_pass: !vault |

You can create here you DB variables

Kind Regards
Luis
